on:
    schedule:
     - cron: '10 0/2 * * *'
    workflow_dispatch:

name: Flood forecast data
  
jobs:
  render:
    name: Pull latest data, update map
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install rgdal
        run: |
          brew install rgdal
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("tidyverse", "tidycensus", "readr", "plyr", "stringr", "dplyr", "leaflet", "leaflet.providers", "htmlwidgets", "RCurl", "sp", "Hmisc", "leafgl", "colourvalues", "sf", "leaflet.extras", "tigris", "reactable", "rmarkdown", "htmltools", "knitr", "RJSONIO", "rjson", "jsonlite", "devtools", "lubridate"))'
      - name: Get flooding forecast info
        run: Rscript WPVI_flood_map.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Update charts' || echo "No changes"
          git push origin || echo "No changes to commit"
