on:
    schedule:
     - cron: '* * * * *'
    workflow_dispatch:

name: Snowfall reports last 24 hours
  
jobs:
  render:
    name: Pull latest data, update map
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install gdal
        run: |
          brew install gdal
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("tidyverse", "stringr", "leaflet", "leaflet.providers", "htmlwidgets", "colourvalues", "sf", "leaflet.extras", "tigris", "rmarkdown", "htmltools", "lubridate"))'
      - name: Get snow info
        run: Rscript snow-precip-map.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Update charts' || echo "No changes"
          git push origin || echo "No changes to commit"
